train:
  batch_size: 8
  learning_rate: 0.0001
  max_epochs: 30
  device: "cuda"
  data_path: "data.json"
  train_data_path: "../data/train_data.json"
  val_data_path: "../data/val_data.json"
  test_data_path: "../data/test_data.json"
