train:
  batch_size: 8
  checkpoint_path: "models/checkpoint.pth"
  data_path: "data/data.json"
  test_data_path: "data/val_data.json"
  train_data_path: "./data/train_data.json"
  val_data_path: "./data/val_data.json"
  learning_rate: 0.00005
  max_epochs: 10
eval:
  grading_model: "base_model"
  tree_overall_model: "data/y_overall_model.joblib"
  tree_recommend_hiring_model: "data/y_recommend_hiring_model.joblib"
  tree_structured_answers_model: "data/y_structured_answers_model.joblib"

